version: '2'
services:
  # jenkins:
  #   image: jenkins
  #   ports:
  #     - "7999:8080"
  #     - "50000:50000"
  #   volumes:
  #     - /var/data/jenkins
  ifish-db:
    image: mysql:5.5
    ports:
      - "13306:3306"
    restart: always
    volumes:
      - ./data/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=2zhlmcl@1hblsqt
      - MYSQL_DATABASE=ifish
  ifish-api:
    depends_on:
      - ifish-db
    build: ./ifish-api
    ports:
      - "8080:8080"
    volumes:
      - ./data/log:/var/log
    links:
      - ifish-db
    restart: always
  ifish-fe:
    depends_on:
      - ifish-api
    build: ./ifish-fe
    volumes:
      # 注意./路径是相对compose.yml的，如果没有./则是代表docker内部自动生成的data volume
      - ./ifish-fe/dist-fe-ui:/usr/share/nginx/html
      - ./ifish-fe/dist-fe-admin:/usr/share/nginx/html/admin
      - ./ifish-fe/ifishimage:/usr/share/nginx/ifishimage
    ports:
      - "8123:80"
    links:
      - ifish-api
    restart: always


