version: '2'
services:
  # jenkins:
  #   image: jenkins
  #   ports:
  #     - "7999:8080"
  #     - "50000:50000"
  #   volumes:
  #     - /var/data/jenkins
  ifish-db:
    image: mysql:5.5
    ports:
      - "13306:3306"
    restart: always
    volumes:
      - ./data/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=2zhlmcl@1hblsqt
      - MYSQL_DATABASE=ifish
  ifish-api:
    depends_on:
      - ifish-db
    build: ./ifish-api
    ports:
      - "8080:8080"
    volumes:
      - ./data/log:/var/log
    links:
      - ifish-db
  


